/*This file contains string for each of the action types which are used throughout the app.*/

export const REG_ACTION='REGISTER_USER';
export const REG_SUC='REGISTER_SUCCESS';
export const REG_FAL='REGISTER_FAILURE';
export const REG_RESET='REGISTER_RESET';

export const LOGIN_ACTION='LOGIN_USER';
export const LOGIN_SUC='LOGIN_SUCCESS';
export const LOGIN_FAL='LOGIN_FAILURE';
export const LOGIN_LOGOUT='LOGIN_LOGOUT';

export const FETCH_NEWS_ACTION='FETCH_NEWS_ACTION';
export const FETCH_NEWS_SUCS='FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL='FETCH_NEWS_FAIL';
export const FETCH_NEWS_RESET='FETCH_NEWS_RESET';


export const CUSTOM_NEWS_ACTION='CUSTOM_NEWS_ACTION';
export const CUSTOM_NEWS_SUCS='CUSTOM_NEWS_SUCS';
export const CUSTOM_NEWS_FAIL='CUSTOM_NEWS_FAIL';
export const CUSTOM_NEWS_RESET='CUSTOM_NEWS_RESET';

export const FETCH_COMMENTS_ACTION='FETCH_COMMENTS_ACTION';
export const FETCH_COMMENTS_SUCS='FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL='FETCH_COMMENTS_FAIL';
export const FETCH_COMMENTS_RESET='FETCH_COMMENTS_RESET';

export const REFRESH_TOKEN_ACTION='REFRESH_TOKEN_ACTION';
export const REFRESH_TOKEN_SUCCESS='REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE='REFRESH_TOKEN_FAILURE';